#include "iomux-mx6q.h"

#define INTERNAL_SERIAL_ENABLED

/******************************************************************
*	 CUSTOM MACRO DEFINITION
*
*    IOMUXPAD explanation
*	 (mux address, pad address, mux, 0x0000, 0, pad values)
******************************************************************/

// SAM3X erase
#define MX6Q_PAD_DISP0_DAT0__GPIO_4_21_PULLDOWN	\
		(IOMUX_PAD(0x0484, 0x0170, 5, 0x0000, 0, 0x30B1))
// arduino pinout pin 12
#define MX6Q_PAD_GPIO_3__GPIO_1_3_PULLDOWN \
		(IOMUX_PAD(0x05FC, 0x022C, 5, 0x0000, 0, 0x30B1))
// Touch interrupt
#define MX6Q_PAD_SD2_DAT2__GPIO_1_13_47KPULLUPPED \
		(MX6Q_PAD_SD2_DAT2__GPIO_1_13 | MUX_PAD_CTRL(PAD_CTL_PUS_47K_UP))
// usb otg selector
#define MX6Q_PAD_EIM_WAIT__GPIO_5_0_CORRECT \
		(IOMUX_PAD(0x0468, 0x0154, 5, 0x0000, 0, 0xB0B1))
// SAM3X otg vbus_enable
#define MX6Q_PAD_GPIO_16__GPIO_7_11_CORRECT \
		(IOMUX_PAD(0x0618, 0x0248, 5, 0x0000, 0, 0xB0B1))

// internal gpios definition	
#define MX6Q_PAD_SD2_DAT0__GPIO_MODE		IMX_GPIO_NR(1, 15)
#define MX6Q_PAD_SD2_DAT2__GPIO_MODE		IMX_GPIO_NR(1, 13) 
#define MX6Q_PAD_EIM_EB2__GPIO_MODE			IMX_GPIO_NR(2, 30) 
#define MX6Q_PAD_EIM_EB3__GPIO_MODE			IMX_GPIO_NR(2, 31)
#define MX6Q_PAD_SD3_DAT5__GPIO_MODE		IMX_GPIO_NR(7, 0) 
#define MX6Q_PAD_DISP0_DAT5__GPIO_MODE		IMX_GPIO_NR(4, 26) 
#define MX6Q_PAD_GPIO_0__GPIO_MODE			IMX_GPIO_NR(1, 0) 
#define MX6Q_PAD_GPIO_2__GPIO_MODE			IMX_GPIO_NR(1, 2)  
#define MX6Q_PAD_GPIO_4__GPIO_MODE			IMX_GPIO_NR(1, 4)  
#define MX6Q_PAD_EIM_WAIT__GPIO_MODE		IMX_GPIO_NR(5, 0)  
#define MX6Q_PAD_GPIO_16__GPIO_MODE			IMX_GPIO_NR(7, 11) 
#define MX6Q_PAD_GPIO_17__GPIO_MODE			IMX_GPIO_NR(7, 12)
#define MX6Q_PAD_NANDF_CS0__GPIO_MODE		IMX_GPIO_NR(6, 11)
#define MX6Q_PAD_NANDF_D5__GPIO_MODE		IMX_GPIO_NR(2, 5)  
#define MX6Q_PAD_SD4_DAT7__GPIO_MODE		IMX_GPIO_NR(2, 15) 
#define MX6Q_PAD_CSI0_DAT19__GPIO_MODE		IMX_GPIO_NR(6, 5)  
#define MX6Q_PAD_CSI0_DAT18__GPIO_MODE		IMX_GPIO_NR(6, 4) 
#define MX6Q_PAD_DISP0_DAT0__GPIO_MODE		IMX_GPIO_NR(4, 21) 
#define MX6Q_PAD_CSIO_DAT18__GPIO_MODE		IMX_GPIO_NR(6, 4) 
#define MX6Q_PAD_CSIO_PIXCLK__GPIO_MODE		IMX_GPIO_NR(5, 18) 
#define MX6Q_PAD_CSIO_DAT17__GPIO_MODE		IMX_GPIO_NR(6, 3)  
#define MX6Q_PAD_NANDF_D4__GPIO_MODE		IMX_GPIO_NR(2, 4)  
#define MX6Q_PAD_EIM_A19__GPIO_MODE			IMX_GPIO_NR(2, 19) 

#define MX6Q_PAD_KEY_ROW0__GPIO_MODE		IMX_GPIO_NR(4, 7)
#define MX6Q_PAD_KEY_COL0__GPIO_MODE		IMX_GPIO_NR(4, 6)

// external pinout gpios definition
#define	MX6Q_PAD_CSI0_DAT11__GPIO_MODE  	IMX_GPIO_NR(5, 29)
#define	MX6Q_PAD_CSI0_DAT10__GPIO_MODE 	  	IMX_GPIO_NR(5, 28)

#define MX6Q_PAD_SD1_CLK__GPIO_MODE			IMX_GPIO_NR(1, 20)	
#define MX6Q_PAD_SD1_DAT0__GPIO_MODE		IMX_GPIO_NR(1, 16)	

#define	MX6Q_PAD_SD1_DAT1__GPIO_MODE   		IMX_GPIO_NR(1, 17)
#define	MX6Q_PAD_SD1_CMD__GPIO_MODE   		IMX_GPIO_NR(1, 18)
#define	MX6Q_PAD_SD4_DAT1__GPIO_MODE   		IMX_GPIO_NR(2, 9)	
#define	MX6Q_PAD_SD4_DAT2__GPIO_MODE   		IMX_GPIO_NR(2, 10)

#define	MX6Q_PAD_SD1_DAT3__GPIO_MODE   		IMX_GPIO_NR(1, 21)  
#define	MX6Q_PAD_SD1_DAT2__GPIO_MODE   		IMX_GPIO_NR(1, 19)
#define	MX6Q_PAD_GPIO_1__GPIO_MODE   		IMX_GPIO_NR(1, 1)
#define	MX6Q_PAD_GPIO_9__GPIO_MODE   		IMX_GPIO_NR(1, 9)	
#define	MX6Q_PAD_GPIO_3__GPIO_MODE   		IMX_GPIO_NR(1, 3)
#define	MX6Q_PAD_SD4_DAT0__GPIO_MODE   		IMX_GPIO_NR(2, 8)

#define	MX6Q_PAD_EIM_D21__GPIO_MODE   		IMX_GPIO_NR(3, 21)
#define	MX6Q_PAD_EIM_D28__GPIO_MODE   		IMX_GPIO_NR(3, 28)
#define	MX6Q_PAD_CSI0_DAT13__GPIO_MODE   	IMX_GPIO_NR(5, 31)	
#define	MX6Q_PAD_CSI0_DAT12__GPIO_MODE   	IMX_GPIO_NR(5, 30)
#define	MX6Q_PAD_CSI0_DAT15__GPIO_MODE   	IMX_GPIO_NR(6, 1)
#define	MX6Q_PAD_CSI0_DAT14__GPIO_MODE   	IMX_GPIO_NR(6, 0)
#define	MX6Q_PAD_CSI0_DAT16__GPIO_MODE   	IMX_GPIO_NR(6, 2)	
#define	MX6Q_PAD_CSI0_DAT4__GPIO_MODE   	IMX_GPIO_NR(5, 22)
#define	MX6Q_PAD_DISP0_DAT6__GPIO_MODE   	IMX_GPIO_NR(4, 27)
#define	MX6Q_PAD_DISP0_DAT7__GPIO_MODE   	IMX_GPIO_NR(4, 28)
#define	MX6Q_PAD_DISP0_DAT8__GPIO_MODE   	IMX_GPIO_NR(4, 29)
#define	MX6Q_PAD_DISP0_DAT9__GPIO_MODE   	IMX_GPIO_NR(4, 30)
#define	MX6Q_PAD_DISP0_DAT10__GPIO_MODE   	IMX_GPIO_NR(4, 31)
#define	MX6Q_PAD_DISP0_DAT11__GPIO_MODE   	IMX_GPIO_NR(5, 5)
#define	MX6Q_PAD_DISP0_DAT12__GPIO_MODE   	IMX_GPIO_NR(5, 6)
#define	MX6Q_PAD_DISP0_DAT13__GPIO_MODE   	IMX_GPIO_NR(5, 7)
#define	MX6Q_PAD_DISP0_DAT14__GPIO_MODE   	IMX_GPIO_NR(5, 8)
#define	MX6Q_PAD_DISP0_DAT15__GPIO_MODE   	IMX_GPIO_NR(5, 9)
#define	MX6Q_PAD_DISP0_DAT16__GPIO_MODE   	IMX_GPIO_NR(5, 10)
#define	MX6Q_PAD_DISP0_DAT17__GPIO_MODE   	IMX_GPIO_NR(5, 11)
#define	MX6Q_PAD_DISP0_DAT18__GPIO_MODE   	IMX_GPIO_NR(5, 12)
#define	MX6Q_PAD_DISP0_DAT19__GPIO_MODE   	IMX_GPIO_NR(5, 13)
#define	MX6Q_PAD_DISP0_DAT20__GPIO_MODE   	IMX_GPIO_NR(5, 14)
#define	MX6Q_PAD_DISP0_DAT21__GPIO_MODE   	IMX_GPIO_NR(5, 15)
#define	MX6Q_PAD_EIM_A16__GPIO_MODE   		IMX_GPIO_NR(2, 22)
#define	MX6Q_PAD_GPIO_18__GPIO_MODE 		IMX_GPIO_NR(7, 13)
#define	MX6Q_PAD_NANDF_D0__GPIO_MODE   		IMX_GPIO_NR(2, 0)	
#define	MX6Q_PAD_NANDF_D1__GPIO_MODE   		IMX_GPIO_NR(2, 1)	
#define	MX6Q_PAD_NANDF_D2__GPIO_MODE   		IMX_GPIO_NR(2, 2)	
#define	MX6Q_PAD_NANDF_D3__GPIO_MODE   		IMX_GPIO_NR(2, 3)	
#define	MX6Q_PAD_GPIO_19__GPIO_MODE   		IMX_GPIO_NR(4, 5)	
#define	MX6Q_PAD_DISP0_DAT22__GPIO_MODE 	IMX_GPIO_NR(5, 16) 	
#define	MX6Q_PAD_DISP0_DAT23__GPIO_MODE  	IMX_GPIO_NR(5, 17) 	
#define	MX6Q_PAD_EIM_D25__GPIO_MODE   		IMX_GPIO_NR(3, 25)	
#define	MX6Q_PAD_KEY_ROW1__GPIO_MODE   		IMX_GPIO_NR(4, 9) 	
#define	MX6Q_PAD_KEY_COL1__GPIO_MODE   		IMX_GPIO_NR(4, 8)	
#define	MX6Q_PAD_EIM_OE__GPIO_MODE   		IMX_GPIO_NR(2, 25)	
#define	MX6Q_PAD_EIM_CS1__GPIO_MODE   		IMX_GPIO_NR(2, 24)	
#define	MX6Q_PAD_EIM_CS0__GPIO_MODE   		IMX_GPIO_NR(2, 23) 	
#define	MX6Q_PAD_EIM_D24__GPIO_MODE   		IMX_GPIO_NR(3, 24)
#define MX6Q_PAD_GPIO_7__GPIO_MODE			IMX_GPIO_NR(1, 7)	
#define MX6Q_PAD_GPIO_8__GPIO_MODE			IMX_GPIO_NR(1, 8)	


static iomux_v3_cfg_t mx6qd_seco_UDOO_pads[] = {
// removed 
};

static unsigned int mx6q_set_in_outputmode_low[] = {
	MX6Q_PAD_SD2_DAT0__GPIO_MODE,  
	MX6Q_PAD_GPIO_16__GPIO_MODE,
	MX6Q_PAD_CSI0_DAT19__GPIO_MODE,
	MX6Q_PAD_EIM_A19__GPIO_MODE,	
	MX6Q_PAD_SD4_DAT7__GPIO_MODE,
	MX6Q_PAD_CSIO_DAT18__GPIO_MODE,
	MX6Q_PAD_EIM_WAIT__GPIO_MODE,	
};

static unsigned int mx6q_set_in_outputmode_high[] = {
	MX6Q_PAD_GPIO_0__GPIO_MODE,
	MX6Q_PAD_NANDF_D5__GPIO_MODE,
	MX6Q_PAD_EIM_EB3__GPIO_MODE,
	MX6Q_PAD_NANDF_CS0__GPIO_MODE,
};

static unsigned int mx6q_set_in_inputmode[] = {	
	MX6Q_PAD_SD2_DAT2__GPIO_MODE,
	MX6Q_PAD_SD3_DAT5__GPIO_MODE,
	MX6Q_PAD_DISP0_DAT0__GPIO_MODE,	
	MX6Q_PAD_DISP0_DAT5__GPIO_MODE,  	
	MX6Q_PAD_CSIO_PIXCLK__GPIO_MODE,	
	MX6Q_PAD_CSIO_DAT17__GPIO_MODE,	

#ifndef INTERNAL_SERIAL_ENABLED	
	MX6Q_PAD_KEY_ROW0__GPIO_MODE,
	MX6Q_PAD_KEY_COL0__GPIO_MODE,
#endif

	MX6Q_PAD_CSI0_DAT10__GPIO_MODE,
	MX6Q_PAD_CSI0_DAT11__GPIO_MODE,	
	MX6Q_PAD_SD1_CLK__GPIO_MODE,	
	MX6Q_PAD_SD1_DAT0__GPIO_MODE,  
	
	MX6Q_PAD_SD1_DAT1__GPIO_MODE,   		
	MX6Q_PAD_SD1_CMD__GPIO_MODE,   		
	MX6Q_PAD_SD4_DAT1__GPIO_MODE,   			
	MX6Q_PAD_SD4_DAT2__GPIO_MODE,
	MX6Q_PAD_SD1_DAT3__GPIO_MODE,

	MX6Q_PAD_SD1_DAT2__GPIO_MODE,   		
	MX6Q_PAD_GPIO_1__GPIO_MODE,   		
	MX6Q_PAD_GPIO_9__GPIO_MODE,   			
	MX6Q_PAD_GPIO_3__GPIO_MODE,   		
	MX6Q_PAD_SD4_DAT0__GPIO_MODE,   		

	MX6Q_PAD_EIM_D21__GPIO_MODE,   
	MX6Q_PAD_EIM_D28__GPIO_MODE,   		
	MX6Q_PAD_CSI0_DAT13__GPIO_MODE,   
	MX6Q_PAD_CSI0_DAT12__GPIO_MODE,  
	MX6Q_PAD_CSI0_DAT15__GPIO_MODE, 
  
	MX6Q_PAD_CSI0_DAT14__GPIO_MODE,   
	MX6Q_PAD_CSI0_DAT16__GPIO_MODE,  
	MX6Q_PAD_CSI0_DAT4__GPIO_MODE, 
	MX6Q_PAD_DISP0_DAT6__GPIO_MODE,   
	MX6Q_PAD_DISP0_DAT7__GPIO_MODE,
   	
	MX6Q_PAD_DISP0_DAT8__GPIO_MODE,   	
	MX6Q_PAD_DISP0_DAT9__GPIO_MODE,  
	MX6Q_PAD_DISP0_DAT10__GPIO_MODE,   
	MX6Q_PAD_DISP0_DAT11__GPIO_MODE,   	
	MX6Q_PAD_DISP0_DAT12__GPIO_MODE, 
  
	MX6Q_PAD_DISP0_DAT13__GPIO_MODE,   
	MX6Q_PAD_DISP0_DAT14__GPIO_MODE,   
	MX6Q_PAD_DISP0_DAT15__GPIO_MODE,   	
	MX6Q_PAD_DISP0_DAT16__GPIO_MODE,   
	MX6Q_PAD_DISP0_DAT17__GPIO_MODE,
  
	MX6Q_PAD_DISP0_DAT18__GPIO_MODE,   
	MX6Q_PAD_DISP0_DAT19__GPIO_MODE,   
	MX6Q_PAD_DISP0_DAT20__GPIO_MODE,   
	MX6Q_PAD_DISP0_DAT21__GPIO_MODE,   	
	MX6Q_PAD_EIM_A16__GPIO_MODE,
	
	MX6Q_PAD_GPIO_18__GPIO_MODE, 	
	MX6Q_PAD_NANDF_D0__GPIO_MODE,   		
	MX6Q_PAD_NANDF_D1__GPIO_MODE,   
	MX6Q_PAD_NANDF_D2__GPIO_MODE,   
	MX6Q_PAD_NANDF_D3__GPIO_MODE, 
  	
	MX6Q_PAD_GPIO_19__GPIO_MODE,   		
	MX6Q_PAD_DISP0_DAT22__GPIO_MODE, 
	MX6Q_PAD_DISP0_DAT23__GPIO_MODE, 	
	MX6Q_PAD_EIM_D25__GPIO_MODE,   		
	MX6Q_PAD_KEY_ROW1__GPIO_MODE,
    	
	MX6Q_PAD_KEY_COL1__GPIO_MODE,  	
	MX6Q_PAD_EIM_OE__GPIO_MODE,   	
	MX6Q_PAD_EIM_CS1__GPIO_MODE,   	
	MX6Q_PAD_EIM_CS0__GPIO_MODE,    		
	MX6Q_PAD_EIM_D24__GPIO_MODE,  

	MX6Q_PAD_GPIO_8__GPIO_MODE,
	MX6Q_PAD_GPIO_7__GPIO_MODE,
};


#define MX6Q_USDHC_PAD_SETTING(id, speed)	\
mx6q_sd##id##_##speed##mhz[] = {		\
	MX6Q_PAD_SD##id##_CLK__USDHC##id##_CLK_##speed##MHZ,	\
	MX6Q_PAD_SD##id##_CMD__USDHC##id##_CMD_##speed##MHZ,	\
	MX6Q_PAD_SD##id##_DAT0__USDHC##id##_DAT0_##speed##MHZ,	\
	MX6Q_PAD_SD##id##_DAT1__USDHC##id##_DAT1_##speed##MHZ,	\
	MX6Q_PAD_SD##id##_DAT2__USDHC##id##_DAT2_##speed##MHZ,	\
	MX6Q_PAD_SD##id##_DAT3__USDHC##id##_DAT3_##speed##MHZ,	\
}
